chore: proposition
DNUM-SocialGouv/documentation pull request #9
Opened 2024-11-07 12:57 UTC by yakhatape

Ajout préco sécurité

2024-11-13 10:59 UTC, achauve requested changes

2024-11-13 10:59 UTC, achauve commented on DevSecOps/securite.md
> +- [ ] signé l'intégralité des commits via des clés gpg/gpg2
typo signer

2024-11-13 10:59 UTC, achauve commented on DevSecOps/securite.md
> +- [ ] signé l'intégralité des commits via des clés gpg/gpg2
je rajouterais ssh, on peut signer ses commits via la clé ssh maintenant sur github

2024-11-13 10:59 UTC, achauve commented on DevSecOps/securite.md
> +  - ceci à des fins de truster la source des commits et/ou d'identifier le développeur
```suggestion
  - objectif : certifier l'auteur des commits
```

2024-11-13 10:59 UTC, achauve commented on DevSecOps/securite.md
> +### Checklist
```suggestion
### Checklist

```

2024-11-13 11:22 UTC, ad-mcas commented on DevSecOps/securite.md
> +- [ ] signé l'intégralité des commits via des clés gpg/gpg2
Je propose d'être plus global pour permettre d autre façon (ex s/mime). Ex:
Signer l'intégralité des commits (via clés gpg2, ssh, s/mime etc...)

2024-11-26 14:57 UTC, achauve commented on DevSecOps/securite.md
> +- [ ] signé l'intégralité des commits via des clés gpg/gpg2
```suggestion

- [ ] signer l'intégralité des commits via des clés gpg / ssh / autre
```

2024-11-26 14:58 UTC, merged